baseURL: https://eatyourexam.com
disablePathToLower: true
languageCode: en-us
title: eatyourexam
theme: bare
params:
  description: a blog about tech, gaming, odds, and ends
  email: rob@eatyourexam.com

